---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caf-server
  labels:
    app: caf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caf-server
  template:
    metadata:
      labels:
        app: caf-server
    spec:
      containers:
        - name: caf-server
          imagePullPolicy: Always
          image: gcr.io/cards-against-friends-277922/caf-server:v1.0.0
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: caf-server-graphql
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31083
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: caf-server-graphql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
